### ISSUE TITLE
Use correct aspect ratio for Strava

### ISSUE THREAD

**Issue by philwilks** [philwilks/ZwiftIRL#15]
Long term this is where most people will post pics I think. At the moment the sides get cropped off in the app. 

- [ ] Ask people to share screenshots of the Strava app on different devices
- [ ] Hopefully they will all be the same aspect ratio?
- [ ] Change the height to match

**Comment by philwilks** [comment]
![E3C55239-C237-4662-8AA4-71A876E3AF04](https://user-images.githubusercontent.com/7359829/108918502-6549bc80-7629-11eb-89ca-ca603f4d2ca8.jpeg)

**Comment by timheuer** [comment]
In reality that's just the preview thumbnail, someone clicking on that in the app would see the full image in both app and web, might be okay?

**Comment by philwilks** [comment]
True – it just bothers me that you can't see it in all it's glory. I've noticed it applies to the screenshots generated by Zwift too though.
